[package]
authors = ["blacknon <blacknon@orebibou.com>"]
description = "A modern alternative to the watch command, records the differences in execution results and can check this differences at after."
edition = "2021"
keywords = ["watch", "command", "monitoring"]
license-file = "LICENSE"
name = "hwatch"
repository = "https://github.com/blacknon/hwatch"
version = "0.3.11"

[dependencies]
# TODO: [ansi-parser](https://crates.io/crates/ansi-parser)のバージョンアップ対応が必要になるので、その対応待ち. PRはmargeされたのでいい加減アップデートされてもいいと思うのだが….
# ansi-parser = {version = "0.9.0", path = "../ansi-parser"}
ansi-parser = "0.8.0"
async-std = {version = "1.12"}
chrono = "0.4.34"
clap = {version = "3.1.18", features = ["cargo"]}
crossbeam-channel = "0.5.12"
crossterm = "0.27.0"
ctrlc = {version = "3.4.2", features = ["termination"]}
difference = "2.0"
futures = "0.3.30"
question = "0.2.2"

# tui = {version = "0.19.0", default-features = false, features = ['crossterm']}
ratatui = {version = "0.26.1", default-features = false, features = ['crossterm']}

regex = "1.10.3"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
shell-words = "1.1.0"

# TODO: ansi-parserのバージョンアップグレードの対応が必要になるので、その対応をしたらバージョンアップが必要.
heapless = "0.5.6"
termwiz = "0.15.0"
