[package]
name = "hwatch"
version = "0.1.0"
authors = ["blacknon <blacknon@orebibou.com>"]
description = "alternative watch command."

[dependencies]
chrono = "0.4"
clap = "2.20.3"
ncurses = "5.91.0"
