[package]
authors = ["blacknon <blacknon@orebibou.com>"]
description = "A modern alternative to the watch command, records the differences in execution results and can check this differences at after."
edition = "2021"
keywords = ["watch", "command", "monitoring"]
license-file = "LICENSE"
name = "hwatch"
repository = "https://github.com/blacknon/hwatch"
version = "0.3.15"

[dependencies]
ansi-parser = "0.9.0"
ansi_term = "0.12.1"
async-std = {version = "1.12"}
chardetng = "0.1.17"
chrono = "0.4.34"
clap = {version = "4.5.3", features = ["cargo"]}
config = {version = "0.14", default-features = false, features = ["ini"]}
crossbeam-channel = "0.5.12"
crossterm = "0.27.0"
ctrlc = {version = "3.4.2", features = ["termination"]}
encoding_rs = "0.8"
error-stack = "0.4.1"
flate2 = "1.0.19"
futures = "0.3.30"
heapless = "0.8.0"
question = "0.2.2"
ratatui = {version = "0.26.1", default-features = false, features = ['crossterm', 'unstable-rendered-line-info']}
regex = "1.10.3"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
shell-words = "1.1.0"
similar = {version = "2.5.0", features = ["serde", "unicode", "text", "inline", "bytes"]}
termwiz = "0.22.0"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-{ version }.{ target }.{ archive-format }"
bin-dir = "bin/{ bin }{ binary-ext }"
